package com.coin;

import com.coin.domain.Coin;
import com.coin.repository.CoinRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@RequiredArgsConstructor
@Component
public class DataLoader implements ApplicationRunner {

    private final CoinRepository coinRepository;

    @Override
    @Transactional
    public void run(ApplicationArguments args) throws Exception {
        coinRepository.save(new Coin("KRW-BTC", "비트코인"));
        coinRepository.save(new Coin("KRW-XRP", "리플"));
        coinRepository.save(new Coin("KRW-STX", "스택스"));
        coinRepository.save(new Coin("KRW-SEI", "세이"));
        coinRepository.save(new Coin("KRW-SC", "시아코인"));
        coinRepository.save(new Coin("KRW-SOL", "솔라나"));
        coinRepository.save(new Coin("KRW-IOTA", "아이오타"));
        coinRepository.save(new Coin("KRW-MLK", "밀크"));
        coinRepository.save(new Coin("KRW-FLOW", "플로우"));
        coinRepository.save(new Coin("KRW-BLUR", "블러"));
        coinRepository.save(new Coin("KRW-DOGE", "도지코인"));
        coinRepository.save(new Coin("KRW-ETH", "이더리움"));
        coinRepository.save(new Coin("KRW-EGLD", "멀티버스엑스"));
        coinRepository.save(new Coin("KRW-MASK", "마스크네트워크"));
        coinRepository.save(new Coin("KRW-BCH", "비트코인캐시"));
        coinRepository.save(new Coin("KRW-ETC", "이더리움클래식"));
        coinRepository.save(new Coin("KRW-NEAR", "니어프로토콜"));
        coinRepository.save(new Coin("KRW-T", "쓰레스홀드"));
        coinRepository.save(new Coin("KRW-ORBS", "오브스"));
        coinRepository.save(new Coin("KRW-SUI", "수이"));
        coinRepository.save(new Coin("KRW-GMT", "스테픈"));
        coinRepository.save(new Coin("KRW-MINA", "미나"));
        coinRepository.save(new Coin("KRW-MTL", "메탈"));
        coinRepository.save(new Coin("KRW-SAND", "샌드박스"));
        coinRepository.save(new Coin("KRW-BTG", "비트코인골드"));
        coinRepository.save(new Coin("KRW-ELF", "엘프"));
        coinRepository.save(new Coin("KRW-AXS", "엑시인피니티"));
        coinRepository.save(new Coin("KRW-BAT", "베이직어텐션토큰"));
        coinRepository.save(new Coin("KRW-BORA", "보라"));
        coinRepository.save(new Coin("KRW-SXP", "솔라"));
        coinRepository.save(new Coin("KRW-LOOM", "룸네트워크"));
        coinRepository.save(new Coin("KRW-AVAX", "아발란체"));
        coinRepository.save(new Coin("KRW-ARB", "아비트럼"));
        coinRepository.save(new Coin("KRW-MVL", "엠블"));
        coinRepository.save(new Coin("KRW-IMX", "이뮤터블엑스"));
        coinRepository.save(new Coin("KRW-HIFI", "하이파이"));
        coinRepository.save(new Coin("KRW-ADA", "에이다"));
        coinRepository.save(new Coin("KRW-LINK", "체인링크"));
        coinRepository.save(new Coin("KRW-MATIC", "폴리곤"));
        coinRepository.save(new Coin("KRW-KAVA", "카바"));
        coinRepository.save(new Coin("KRW-STORJ", "스토리지"));
        coinRepository.save(new Coin("KRW-SBD", "스팀달러"));
        coinRepository.save(new Coin("KRW-CHZ", "칠리즈"));
        coinRepository.save(new Coin("KRW-GAS", "가스"));
        coinRepository.save(new Coin("KRW-EOS", "이오스"));
        coinRepository.save(new Coin("KRW-MANA", "디센트럴랜드"));
        coinRepository.save(new Coin("KRW-PLA", "플레이댑"));
        coinRepository.save(new Coin("KRW-META", "메타디움"));
        coinRepository.save(new Coin("KRW-ALGO", "알고랜드"));
        coinRepository.save(new Coin("KRW-APT", "앱토스"));
        coinRepository.save(new Coin("KRW-BSV", "비트코인에스브이"));
        coinRepository.save(new Coin("KRW-1INCH", "1인치네트워크"));
        coinRepository.save(new Coin("KRW-STRAX", "스트라티스"));
        coinRepository.save(new Coin("KRW-DOT", "폴카닷"));
        coinRepository.save(new Coin("KRW-NEO", "네오"));
        coinRepository.save(new Coin("KRW-CRE", "캐리프로토콜"));
        coinRepository.save(new Coin("KRW-WAVES", "웨이브"));
        coinRepository.save(new Coin("KRW-TRX", "트론"));
        coinRepository.save(new Coin("KRW-SNT", "스테이터스네트워크토큰"));
        coinRepository.save(new Coin("KRW-STMX", "스톰엑스"));
        coinRepository.save(new Coin("KRW-WAXP", "왁스"));
        coinRepository.save(new Coin("KRW-XLM", "스텔라루멘"));
        coinRepository.save(new Coin("KRW-XEM", "넴"));
        coinRepository.save(new Coin("KRW-QTUM", "퀀텀"));
        coinRepository.save(new Coin("KRW-ATOM", "코스모스"));
        coinRepository.save(new Coin("KRW-AERGO", "아르고"));
        coinRepository.save(new Coin("KRW-XTZ", "테조스"));
        coinRepository.save(new Coin("KRW-MBL", "무비블록"));
        coinRepository.save(new Coin("KRW-POWR", "파워렛저"));
        coinRepository.save(new Coin("KRW-TT", "썬더코어"));
        coinRepository.save(new Coin("KRW-ONT", "온톨로지"));
        coinRepository.save(new Coin("KRW-HUNT", "헌트"));
        coinRepository.save(new Coin("KRW-POLYX", "폴리매쉬"));
        coinRepository.save(new Coin("KRW-ZIL", "질리카"));
        coinRepository.save(new Coin("KRW-GRT", "더그래프"));
        coinRepository.save(new Coin("KRW-ZRX", "제로엑스"));
        coinRepository.save(new Coin("KRW-VET", "비체인"));
        coinRepository.save(new Coin("KRW-GRS", "그로스톨코인"));
        coinRepository.save(new Coin("KRW-KNC", "카이버네트워크"));
        coinRepository.save(new Coin("KRW-STPT", "에스티피"));
        coinRepository.save(new Coin("KRW-HBAR", "헤데라"));
        coinRepository.save(new Coin("KRW-ANKR", "앵커"));
        coinRepository.save(new Coin("KRW-HIVE", "하이브"));
        coinRepository.save(new Coin("KRW-CELO", "셀로"));
        coinRepository.save(new Coin("KRW-IQ", "아이큐"));
        coinRepository.save(new Coin("KRW-ICX", "아이콘"));
        coinRepository.save(new Coin("KRW-TON", "톤"));
        coinRepository.save(new Coin("KRW-PUNDIX", "펀디엑스"));
        coinRepository.save(new Coin("KRW-ARK", "아크"));
        coinRepository.save(new Coin("KRW-JST", "저스트"));
        coinRepository.save(new Coin("KRW-ONG", "온톨로지가스"));
        coinRepository.save(new Coin("KRW-STEEM", "스팀"));
        coinRepository.save(new Coin("KRW-GLM", "골렘"));
        coinRepository.save(new Coin("KRW-MED", "메디블록"));
        coinRepository.save(new Coin("KRW-LSK", "리스크"));
        coinRepository.save(new Coin("KRW-FCT2", "파르마체인"));
        coinRepository.save(new Coin("KRW-DKA", "디카르고"));
        coinRepository.save(new Coin("KRW-AAVE", "에이브"));
        coinRepository.save(new Coin("KRW-MOC", "모스코인"));
        coinRepository.save(new Coin("KRW-HPO", "히포크랏"));
        coinRepository.save(new Coin("KRW-CVC", "시빅"));
        coinRepository.save(new Coin("KRW-SSX", "썸씽"));
        coinRepository.save(new Coin("KRW-STRK", "스트라이크"));
        coinRepository.save(new Coin("KRW-THETA", "쎄타토큰"));
        coinRepository.save(new Coin("KRW-AHT", "아하토큰"));
        coinRepository.save(new Coin("KRW-UPP", "센티넬프로토콜"));
        coinRepository.save(new Coin("KRW-CBK", "코박토큰"));
        coinRepository.save(new Coin("KRW-IOST", "아이오에스티"));
        coinRepository.save(new Coin("KRW-AQT", "알파쿼크"));
        coinRepository.save(new Coin("KRW-QKC", "쿼크체인"));
        coinRepository.save(new Coin("KRW-CRO", "크로노스"));
    }
}
